//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventosCorferias.Resources.RecursosIdioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventosCorferias.Resources.RecursosIdioma.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abril.
        /// </summary>
        internal static string abril {
            get {
                return ResourceManager.GetString("abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto la.
        /// </summary>
        internal static string AceptoLa {
            get {
                return ResourceManager.GetString("AceptoLa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto los.
        /// </summary>
        internal static string aceptoLos {
            get {
                return ResourceManager.GetString("aceptoLos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad.
        /// </summary>
        internal static string actividad {
            get {
                return ResourceManager.GetString("actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actual.
        /// </summary>
        internal static string actual {
            get {
                return ResourceManager.GetString("actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te recomendamos actualizar los datos de tu perfil antes de cerrar sesión, así podrás contar con tu información unificada al ingresar desde otras redes..
        /// </summary>
        internal static string ActualizaDatosPerfil {
            get {
                return ResourceManager.GetString("ActualizaDatosPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aforo:.
        /// </summary>
        internal static string aforo {
            get {
                return ResourceManager.GetString("aforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda.
        /// </summary>
        internal static string agenda {
            get {
                return ResourceManager.GetString("agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agenda del autor.
        /// </summary>
        internal static string agendaDelAutor {
            get {
                return ResourceManager.GetString("agendaDelAutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agosto.
        /// </summary>
        internal static string agosto {
            get {
                return ResourceManager.GetString("agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a al.
        /// </summary>
        internal static string al {
            get {
                return ResourceManager.GetString("al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación de impuestos.
        /// </summary>
        internal static string aplicacionImpuestos {
            get {
                return ResourceManager.GetString("aplicacionImpuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área *.
        /// </summary>
        internal static string areaAst {
            get {
                return ResourceManager.GetString("areaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto.
        /// </summary>
        internal static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El asunto no puede tener más de 50 caracteres.
        /// </summary>
        internal static string asunto50Carac {
            get {
                return ResourceManager.GetString("asunto50Carac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  ¡Puedes hacer ZOOM en la imagen con tus dedos!.
        /// </summary>
        internal static string ayudaZoom {
            get {
                return ResourceManager.GetString("ayudaZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, su código de verificación es: .
        /// </summary>
        internal static string BienvenidoCodigoConfirmacion_ {
            get {
                return ResourceManager.GetString("BienvenidoCodigoConfirmacion ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - boletas, ¿deseas realizar la compra de esta cantidad?.
        /// </summary>
        internal static string boletasDeseasRealizarLaCompra {
            get {
                return ResourceManager.GetString("boletasDeseasRealizarLaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletería.
        /// </summary>
        internal static string Boleteria {
            get {
                return ResourceManager.GetString("Boleteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los campos marcados con * son obligatorios.
        /// </summary>
        internal static string camposObligatorios {
            get {
                return ResourceManager.GetString("camposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dejes campos vacíos*.
        /// </summary>
        internal static string camposVacios {
            get {
                return ResourceManager.GetString("camposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad mínima  a comprar debe ser 1 y la máxima es.
        /// </summary>
        internal static string CantidadMinimaUna {
            get {
                return ResourceManager.GetString("CantidadMinimaUna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string cargo {
            get {
                return ResourceManager.GetString("cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo *.
        /// </summary>
        internal static string cargoAst {
            get {
                return ResourceManager.GetString("cargoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo de productos.
        /// </summary>
        internal static string catalogoDeProductos {
            get {
                return ResourceManager.GetString("catalogoDeProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        internal static string celular {
            get {
                return ResourceManager.GetString("celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string ciudad {
            get {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad *.
        /// </summary>
        internal static string ciudadAst {
            get {
                return ResourceManager.GetString("ciudadAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad de recinto.
        /// </summary>
        internal static string ciudadRecinto {
            get {
                return ResourceManager.GetString("ciudadRecinto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad de recinto *.
        /// </summary>
        internal static string ciudadRecintoAst {
            get {
                return ResourceManager.GetString("ciudadRecintoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string CodigoMarca_ {
            get {
                return ResourceManager.GetString("CodigoMarca ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal.
        /// </summary>
        internal static string codigoPostal {
            get {
                return ResourceManager.GetString("codigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código postal *.
        /// </summary>
        internal static string codigoPostalAst {
            get {
                return ResourceManager.GetString("codigoPostalAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código promocional.
        /// </summary>
        internal static string codigoPromocional {
            get {
                return ResourceManager.GetString("codigoPromocional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código inválido, inténtalo de nuevo.
        /// </summary>
        internal static string codigoPromocionalInvalido {
            get {
                return ResourceManager.GetString("codigoPromocionalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Qr.
        /// </summary>
        internal static string CodigoQrti {
            get {
                return ResourceManager.GetString("CodigoQrti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como llegar.
        /// </summary>
        internal static string comoLlegar {
            get {
                return ResourceManager.GetString("comoLlegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        internal static string comprar {
            get {
                return ResourceManager.GetString("comprar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con el código de verificación de tu cuenta.
        /// </summary>
        internal static string conElCodigoMas {
            get {
                return ResourceManager.GetString("conElCodigoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        internal static string conferencista {
            get {
                return ResourceManager.GetString("conferencista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        internal static string ConferencistaDosPuntos {
            get {
                return ResourceManager.GetString("ConferencistaDosPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        internal static string conferencistaInvitado {
            get {
                return ResourceManager.GetString("conferencistaInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitados.
        /// </summary>
        internal static string conferencistas {
            get {
                return ResourceManager.GetString("conferencistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        internal static string conferensista {
            get {
                return ResourceManager.GetString("conferensista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string confirmarContrasena {
            get {
                return ResourceManager.GetString("confirmarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña *.
        /// </summary>
        internal static string ConfirmarContrasenaAst {
            get {
                return ResourceManager.GetString("ConfirmarContrasenaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar correo electrónico.
        /// </summary>
        internal static string confirmarCorreoElectronico {
            get {
                return ResourceManager.GetString("confirmarCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar correo electrónico *.
        /// </summary>
        internal static string confirmarCorreoElectronicoAst {
            get {
                return ResourceManager.GetString("confirmarCorreoElectronicoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contáctanos.
        /// </summary>
        internal static string Contactanos {
            get {
                return ResourceManager.GetString("Contactanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contamos con -.
        /// </summary>
        internal static string contamosCon {
            get {
                return ResourceManager.GetString("contamosCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jornadas profesionales.
        /// </summary>
        internal static string Contenidos {
            get {
                return ResourceManager.GetString("Contenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        internal static string continuar {
            get {
                return ResourceManager.GetString("continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar con Apple.
        /// </summary>
        internal static string continuarApple {
            get {
                return ResourceManager.GetString("continuarApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar con correo.
        /// </summary>
        internal static string ContinuarCorreo {
            get {
                return ResourceManager.GetString("ContinuarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar con Google.
        /// </summary>
        internal static string ContinuarGoogle {
            get {
                return ResourceManager.GetString("ContinuarGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        internal static string contrasenaActual {
            get {
                return ResourceManager.GetString("contrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña *.
        /// </summary>
        internal static string ContrasenaAst {
            get {
                return ResourceManager.GetString("ContrasenaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        internal static string contrasenaIncorrecta {
            get {
                return ResourceManager.GetString("contrasenaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña no coincide.
        /// </summary>
        internal static string contrasenaNoConincide {
            get {
                return ResourceManager.GetString("contrasenaNoConincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corferias en.
        /// </summary>
        internal static string CorferiasEn {
            get {
                return ResourceManager.GetString("CorferiasEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        internal static string correoElectronico {
            get {
                return ResourceManager.GetString("correoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico *.
        /// </summary>
        internal static string correoElectronicoAst {
            get {
                return ResourceManager.GetString("correoElectronicoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        internal static string CrearCuenta {
            get {
                return ResourceManager.GetString("CrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas vinculadas.
        /// </summary>
        internal static string cuentasVinculadas {
            get {
                return ResourceManager.GetString("cuentasVinculadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuponera.
        /// </summary>
        internal static string cuponera {
            get {
                return ResourceManager.GetString("cuponera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Facturación.
        /// </summary>
        internal static string datosFacturacion {
            get {
                return ResourceManager.GetString("datosFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes tener en cuenta que los cupones son limitados y tienen fecha de vencimiento.
        /// </summary>
        internal static string DebesTenerEnCuentaQueLosCuponesSonLimitado {
            get {
                return ResourceManager.GetString("DebesTenerEnCuentaQueLosCuponesSonLimitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Del.
        /// </summary>
        internal static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de la empresa.
        /// </summary>
        internal static string deLaEmpresa {
            get {
                return ResourceManager.GetString("deLaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción no puede tener más de 50 caracteres.
        /// </summary>
        internal static string Descrip50 {
            get {
                return ResourceManager.GetString("Descrip50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacados.
        /// </summary>
        internal static string destacados {
            get {
                return ResourceManager.GetString("destacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle agenda.
        /// </summary>
        internal static string detalleAgenda {
            get {
                return ResourceManager.GetString("detalleAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle invitado.
        /// </summary>
        internal static string detalleConferencista {
            get {
                return ResourceManager.GetString("detalleConferencista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Jornadas profesionales.
        /// </summary>
        internal static string detalleContenido {
            get {
                return ResourceManager.GetString("detalleContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle expositor.
        /// </summary>
        internal static string detalleExpositor {
            get {
                return ResourceManager.GetString("detalleExpositor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle servicio.
        /// </summary>
        internal static string detalleServicio {
            get {
                return ResourceManager.GetString("detalleServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle sitio.
        /// </summary>
        internal static string detalleSitio {
            get {
                return ResourceManager.GetString("detalleSitio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diciembre.
        /// </summary>
        internal static string diciembre {
            get {
                return ResourceManager.GetString("diciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string direccion {
            get {
                return ResourceManager.GetString("direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección *.
        /// </summary>
        internal static string direccionAst {
            get {
                return ResourceManager.GetString("direccionAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil.
        /// </summary>
        internal static string editarPerfil {
            get {
                return ResourceManager.GetString("editarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El filtro: ¿Qué  estas buscando?, debe contener mínimo  tres caracteres..
        /// </summary>
        internal static string elCampoQueEstasBuscandoEsOblighatorio {
            get {
                return ResourceManager.GetString("elCampoQueEstasBuscandoEsOblighatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * El código registrado no corresponde.
        /// </summary>
        internal static string elCodigoNoMas {
            get {
                return ResourceManager.GetString("elCodigoNoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar usuario.
        /// </summary>
        internal static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de presentar un inconveniente, genere una solicitud de contacto desde el menú de la app.
        /// </summary>
        internal static string EnCasoDePresentarUnInconveniente {
            get {
                return ResourceManager.GetString("EnCasoDePresentarUnInconveniente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero.
        /// </summary>
        internal static string enero {
            get {
                return ResourceManager.GetString("enero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviamos un correo electrónico a.
        /// </summary>
        internal static string enviamosUnCorreoMas {
            get {
                return ResourceManager.GetString("enviamosUnCorreoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado exitosamente.
        /// </summary>
        internal static string EnvioExitoso {
            get {
                return ResourceManager.GetString("EnvioExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hemos podido enviar el formulario.
        /// </summary>
        internal static string EnvioNoExitoso {
            get {
                return ResourceManager.GetString("EnvioNoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible obtener el correo electrónico proporcionado por Apple..
        /// </summary>
        internal static string ErrorAppleDos {
            get {
                return ResourceManager.GetString("ErrorAppleDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpa, estamos teniendo problemas con el acceso. Intenta iniciar sesión con otra red social mientras solucionamos el inconveniente..
        /// </summary>
        internal static string ErrorAppleUno {
            get {
                return ResourceManager.GetString("ErrorAppleUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos tenido un error en el redireccionamiento al crear la cuenta. Reinicia la app o consulta con el administrador..
        /// </summary>
        internal static string ErrorRedireccionarLogin {
            get {
                return ResourceManager.GetString("ErrorRedireccionarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tenemos la feria activa en este momento. Intenta de nuevo más tarde.
        /// </summary>
        internal static string errorSlashdos {
            get {
                return ResourceManager.GetString("errorSlashdos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifica tu conexión a internet e intenta acceder nuevamente a la app.
        /// </summary>
        internal static string ErrorSplahs {
            get {
                return ResourceManager.GetString("ErrorSplahs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hemos podido obtener la validación de Google. Por favor, intenta de nuevo más tarde..
        /// </summary>
        internal static string errroGoogleLogin {
            get {
                return ResourceManager.GetString("errroGoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: .
        /// </summary>
        internal static string estadoDosPuntos {
            get {
                return ResourceManager.GetString("estadoDosPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de eliminar la factura?.
        /// </summary>
        internal static string estasSeguroDeEliminarLaFactura {
            get {
                return ResourceManager.GetString("estasSeguroDeEliminarLaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de eliminar todas las notificaciones?.
        /// </summary>
        internal static string estasSeguroDeEliminarLasNotificaciones {
            get {
                return ResourceManager.GetString("estasSeguroDeEliminarLasNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contamos con resultados para esta búsqueda, revisa más tarde.
        /// </summary>
        internal static string EsteConferencistaNoCuentaAunConAgenda {
            get {
                return ResourceManager.GetString("EsteConferencistaNoCuentaAunConAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este evento fue cancelado.
        /// </summary>
        internal static string esteEventoFueCancelado {
            get {
                return ResourceManager.GetString("esteEventoFueCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluar.
        /// </summary>
        internal static string evaluar {
            get {
                return ResourceManager.GetString("evaluar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento.
        /// </summary>
        internal static string evento {
            get {
                return ResourceManager.GetString("evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expositor.
        /// </summary>
        internal static string expositor {
            get {
                return ResourceManager.GetString("expositor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expositores.
        /// </summary>
        internal static string Expositores {
            get {
                return ResourceManager.GetString("Expositores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Febrero.
        /// </summary>
        internal static string febrero {
            get {
                return ResourceManager.GetString("febrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha: .
        /// </summary>
        internal static string fechaDosPuntos {
            get {
                return ResourceManager.GetString("fechaDosPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        internal static string fechaNacimiento {
            get {
                return ResourceManager.GetString("fechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento *.
        /// </summary>
        internal static string FechaNacimientoAts {
            get {
                return ResourceManager.GetString("FechaNacimientoAts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta funcionalidad no se encuentra disponible..
        /// </summary>
        internal static string FuncionalidadNoDisponible {
            get {
                return ResourceManager.GetString("FuncionalidadNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAR UN CÓDIGO NUEVO.
        /// </summary>
        internal static string generarUnCodigoMas {
            get {
                return ResourceManager.GetString("generarUnCodigoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        internal static string guardarCambios {
            get {
                return ResourceManager.GetString("guardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        internal static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora:.
        /// </summary>
        internal static string hora {
            get {
                return ResourceManager.GetString("hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario.
        /// </summary>
        internal static string horario {
            get {
                return ResourceManager.GetString("horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        internal static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la empresa.
        /// </summary>
        internal static string informacionDeLaEmpresa {
            get {
                return ResourceManager.GetString("informacionDeLaEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información personal.
        /// </summary>
        internal static string informacionPersonal {
            get {
                return ResourceManager.GetString("informacionPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGRESA EL CÓDIGO.
        /// </summary>
        internal static string ingresaElCodigo {
            get {
                return ResourceManager.GetString("ingresaElCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar con Correo.
        /// </summary>
        internal static string ingresaTuCorreo {
            get {
                return ResourceManager.GetString("ingresaTuCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Julio.
        /// </summary>
        internal static string julio {
            get {
                return ResourceManager.GetString("julio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Junio.
        /// </summary>
        internal static string junio {
            get {
                return ResourceManager.GetString("junio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta generada no cuenta con registros.
        /// </summary>
        internal static string laConsultaGeneradaNoCuentaConRegistro {
            get {
                return ResourceManager.GetString("laConsultaGeneradaNoCuentaConRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información de este recinto no está disponible..
        /// </summary>
        internal static string laInformacionDeEsteRecintoNoDisponible {
            get {
                return ResourceManager.GetString("laInformacionDeEsteRecintoNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Franja.
        /// </summary>
        internal static string lblFranja {
            get {
                return ResourceManager.GetString("lblFranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organizador.
        /// </summary>
        internal static string lblOrganizador {
            get {
                return ResourceManager.GetString("lblOrganizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con contraseña asignada, Por Favor actualice su información en el login. Opción - Olvidé mi contraseña.
        /// </summary>
        internal static string loginolvidecontraseña {
            get {
                return ResourceManager.GetString("loginolvidecontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar:.
        /// </summary>
        internal static string lugar {
            get {
                return ResourceManager.GetString("lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenerme conectado.
        /// </summary>
        internal static string mantenerConectado {
            get {
                return ResourceManager.GetString("mantenerConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marzo.
        /// </summary>
        internal static string marzo {
            get {
                return ResourceManager.GetString("marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayo.
        /// </summary>
        internal static string mayo {
            get {
                return ResourceManager.GetString("mayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi agenda.
        /// </summary>
        internal static string miAgenda {
            get {
                return ResourceManager.GetString("miAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis boletas.
        /// </summary>
        internal static string misBoletas {
            get {
                return ResourceManager.GetString("misBoletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis contenidos.
        /// </summary>
        internal static string misContenidos {
            get {
                return ResourceManager.GetString("misContenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis destacados.
        /// </summary>
        internal static string misDestacados {
            get {
                return ResourceManager.GetString("misDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis expositores.
        /// </summary>
        internal static string misExpositores {
            get {
                return ResourceManager.GetString("misExpositores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis invitaciones.
        /// </summary>
        internal static string misinvitaciones {
            get {
                return ResourceManager.GetString("misinvitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis invitados.
        /// </summary>
        internal static string misInvitados {
            get {
                return ResourceManager.GetString("misInvitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En el momento no tenemos boletería disponible para este ítem, intenta de nuevo más tarde..
        /// </summary>
        internal static string noBoleteriaEnElMomento {
            get {
                return ResourceManager.GetString("noBoleteriaEnElMomento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudimos cargar el enlace de esta red social.
        /// </summary>
        internal static string NoCargaEnlaceRedSocial {
            get {
                return ResourceManager.GetString("NoCargaEnlaceRedSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° identificación de la empresa.
        /// </summary>
        internal static string noIdentificacionEmpresa {
            get {
                return ResourceManager.GetString("noIdentificacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        internal static string nombreCompleto {
            get {
                return ResourceManager.GetString("nombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo*.
        /// </summary>
        internal static string NombreCompletoAst {
            get {
                return ResourceManager.GetString("NombreCompletoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la empresa.
        /// </summary>
        internal static string nombreEmpresa {
            get {
                return ResourceManager.GetString("nombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la empresa *.
        /// </summary>
        internal static string nombreEmpresaAst {
            get {
                return ResourceManager.GetString("nombreEmpresaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILBo.
        /// </summary>
        internal static string nombreMarca {
            get {
                return ResourceManager.GetString("nombreMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar la compra, revise la información o intente de nuevo más tarde.
        /// </summary>
        internal static string NoSePuedoRealizarLaCompra {
            get {
                return ResourceManager.GetString("NoSePuedoRealizarLaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        internal static string notificaciones {
            get {
                return ResourceManager.GetString("notificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noviembre.
        /// </summary>
        internal static string noviembre {
            get {
                return ResourceManager.GetString("noviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nuestra experiencia.
        /// </summary>
        internal static string nuestraExperiencia {
            get {
                return ResourceManager.GetString("nuestraExperiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nueva.
        /// </summary>
        internal static string nueva {
            get {
                return ResourceManager.GetString("nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Contraseña.
        /// </summary>
        internal static string nuevaClave {
            get {
                return ResourceManager.GetString("nuevaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de documento.
        /// </summary>
        internal static string numeroDeDocumento {
            get {
                return ResourceManager.GetString("numeroDeDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de documento.
        /// </summary>
        internal static string NumeroDocumento {
            get {
                return ResourceManager.GetString("NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de documento *.
        /// </summary>
        internal static string NumeroDocumentoAst {
            get {
                return ResourceManager.GetString("NumeroDocumentoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° de identificación de la empresa *.
        /// </summary>
        internal static string NumeroIdEmpresaAst {
            get {
                return ResourceManager.GetString("NumeroIdEmpresaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº de identificación de la empresa.
        /// </summary>
        internal static string numIdentificacionEmpresa {
            get {
                return ResourceManager.GetString("numIdentificacionEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octubre.
        /// </summary>
        internal static string octubre {
            get {
                return ResourceManager.GetString("octubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvidé mi contraseña.
        /// </summary>
        internal static string olvideClave {
            get {
                return ResourceManager.GetString("olvideClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagar.
        /// </summary>
        internal static string pagar {
            get {
                return ResourceManager.GetString("pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago boleta.
        /// </summary>
        internal static string pagoBoleta {
            get {
                return ResourceManager.GetString("pagoBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País *.
        /// </summary>
        internal static string paisAst {
            get {
                return ResourceManager.GetString("paisAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País de residencia *.
        /// </summary>
        internal static string PaisRecidenciaAst {
            get {
                return ResourceManager.GetString("PaisRecidenciaAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País de residencia.
        /// </summary>
        internal static string paisResidencia {
            get {
                return ResourceManager.GetString("paisResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participara en.
        /// </summary>
        internal static string participaraen {
            get {
                return ResourceManager.GetString("participaraen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        internal static string paso1 {
            get {
                return ResourceManager.GetString("paso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil del expositor.
        /// </summary>
        internal static string perfilDelExpositor {
            get {
                return ResourceManager.GetString("perfilDelExpositor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a personal.
        /// </summary>
        internal static string personal {
            get {
                return ResourceManager.GetString("personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a política de datos.
        /// </summary>
        internal static string politicaDeDatos {
            get {
                return ResourceManager.GetString("politicaDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a política de tratamiento de datos.
        /// </summary>
        internal static string politicaDeTratamientoDeDatos {
            get {
                return ResourceManager.GetString("politicaDeTratamientoDeDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a politica de tratamiento de datos.
        /// </summary>
        internal static string politicaTrat {
            get {
                return ResourceManager.GetString("politicaTrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por: .
        /// </summary>
        internal static string porDosPunto {
            get {
                return ResourceManager.GetString("porDosPunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pre-registro.
        /// </summary>
        internal static string preRegistro {
            get {
                return ResourceManager.GetString("preRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        internal static string producto {
            get {
                return ResourceManager.GetString("producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesión.
        /// </summary>
        internal static string profesion {
            get {
                return ResourceManager.GetString("profesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesión *.
        /// </summary>
        internal static string ProfesionAst {
            get {
                return ResourceManager.GetString("ProfesionAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quedarme.
        /// </summary>
        internal static string quedarme {
            get {
                return ResourceManager.GetString("quedarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El filtro: ¿Qué  estas buscando?, debe contener mínimo  tres caracteres..
        /// </summary>
        internal static string queEstasBuscando {
            get {
                return ResourceManager.GetString("queEstasBuscando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerde que la búsqueda carga inicialmente con la ciudad registrada y para el año actual..
        /// </summary>
        internal static string recuerdeQueLaBusquedaCargaIncialmente {
            get {
                return ResourceManager.GetString("recuerdeQueLaBusquedaCargaIncialmente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        internal static string recuperarContrasena {
            get {
                return ResourceManager.GetString("recuperarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red social.
        /// </summary>
        internal static string redSocial {
            get {
                return ResourceManager.GetString("redSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registra.
        /// </summary>
        internal static string registra {
            get {
                return ResourceManager.GetString("registra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registra el correo para recuperar tu contraseña.
        /// </summary>
        internal static string registraElCorreoMas {
            get {
                return ResourceManager.GetString("registraElCorreoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        internal static string registrarme {
            get {
                return ResourceManager.GetString("registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reproducir.
        /// </summary>
        internal static string reproducir {
            get {
                return ResourceManager.GetString("reproducir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reproducir contenido.
        /// </summary>
        internal static string reproducirContendo {
            get {
                return ResourceManager.GetString("reproducirContendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultados.
        /// </summary>
        internal static string resultados {
            get {
                return ResourceManager.GetString("resultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de la compra.
        /// </summary>
        internal static string resumenCompra {
            get {
                return ResourceManager.GetString("resumenCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de búsqueda.
        /// </summary>
        internal static string rutaDeBusqueda {
            get {
                return ResourceManager.GetString("rutaDeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se acabo de reenviar el código, revisa tu correo electrónico..
        /// </summary>
        internal static string seAcaboDeReenviarElCodigo {
            get {
                return ResourceManager.GetString("seAcaboDeReenviarElCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector económico.
        /// </summary>
        internal static string sectorEconomico {
            get {
                return ResourceManager.GetString("sectorEconomico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector económico *.
        /// </summary>
        internal static string SectorEconomicoAst {
            get {
                return ResourceManager.GetString("SectorEconomicoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de cerrar sesión?.
        /// </summary>
        internal static string SeguroCerrarSesion {
            get {
                return ResourceManager.GetString("SeguroCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de eliminar el usuario? Esta acción es permanente..
        /// </summary>
        internal static string SeguroEliminarUsu {
            get {
                return ResourceManager.GetString("SeguroEliminarUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro quiere cerrar la aplicación?.
        /// </summary>
        internal static string seguroQuiereCerrarLaAplicacion {
            get {
                return ResourceManager.GetString("seguroQuiereCerrarLaAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se han borrado todas las notificaciones con éxito!.
        /// </summary>
        internal static string SeHanBorradoConExito {
            get {
                return ResourceManager.GetString("SeHanBorradoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string seleccionar {
            get {
                return ResourceManager.GetString("seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma.
        /// </summary>
        internal static string seleccionarIdioma {
            get {
                return ResourceManager.GetString("seleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Septiembre.
        /// </summary>
        internal static string septiembre {
            get {
                return ResourceManager.GetString("septiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio esta en mantenimiento.
        /// </summary>
        internal static string ServicioMantenimiento {
            get {
                return ResourceManager.GetString("ServicioMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        internal static string servicios {
            get {
                return ResourceManager.GetString("servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios generales.
        /// </summary>
        internal static string ServiciosGenerales {
            get {
                return ResourceManager.GetString("ServiciosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Síguenos en.
        /// </summary>
        internal static string SiguenosEn {
            get {
                return ResourceManager.GetString("SiguenosEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitios.
        /// </summary>
        internal static string sitios {
            get {
                return ResourceManager.GetString("sitios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feria / Evento.
        /// </summary>
        internal static string suceso {
            get {
                return ResourceManager.GetString("suceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * Sujeto a cambios sin previo aviso..
        /// </summary>
        internal static string sujetoacambios {
            get {
                return ResourceManager.GetString("sujetoacambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscríbete a nuestro newsletter.
        /// </summary>
        internal static string suscribeteNewlester {
            get {
                return ResourceManager.GetString("suscribeteNewlester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono *.
        /// </summary>
        internal static string telefonoAst {
            get {
                return ResourceManager.GetString("telefonoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono o Celular.
        /// </summary>
        internal static string telefonoCelular {
            get {
                return ResourceManager.GetString("telefonoCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a términos y condiciones.
        /// </summary>
        internal static string terminosYCondiciones {
            get {
                return ResourceManager.GetString("terminosYCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al confirmar el pago de la boleta, usted recibirá una confirmación del pago y sus entradas online en el correo electrónico registrado recuerde revisar su casilla de spam..
        /// </summary>
        internal static string textoBoleteriaDos {
            get {
                return ResourceManager.GetString("textoBoleteriaDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tenga en cuenta: Los datos ingresados en este formulario deben ser los de la persona que va asistir al evento. En caso de comprar varias boletas, el titular deberá presentarse con sus acompañantes al momento de ingresar al evento..
        /// </summary>
        internal static string textoBoleteriaUno {
            get {
                return ResourceManager.GetString("textoBoleteriaUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda virtual.
        /// </summary>
        internal static string tiendaVirtual {
            get {
                return ResourceManager.GetString("tiendaVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de contacto *.
        /// </summary>
        internal static string TipoContacto {
            get {
                return ResourceManager.GetString("TipoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de documento.
        /// </summary>
        internal static string tipoDocumento {
            get {
                return ResourceManager.GetString("tipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de documento *.
        /// </summary>
        internal static string TipoDocumentoAst {
            get {
                return ResourceManager.GetString("TipoDocumentoAst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo y número de documento.
        /// </summary>
        internal static string tiponNumeroIdentificacion {
            get {
                return ResourceManager.GetString("tiponNumeroIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titular de la factura.
        /// </summary>
        internal static string titularFactura {
            get {
                return ResourceManager.GetString("titularFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tu empresa.
        /// </summary>
        internal static string tuEmpresa {
            get {
                return ResourceManager.GetString("tuEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Únete a.
        /// </summary>
        internal static string uneteA {
            get {
                return ResourceManager.GetString("uneteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de la boleta.
        /// </summary>
        internal static string valorBoleta {
            get {
                return ResourceManager.GetString("valorBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor IVA.
        /// </summary>
        internal static string valorIVA {
            get {
                return ResourceManager.GetString("valorIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor total.
        /// </summary>
        internal static string valorTotal {
            get {
                return ResourceManager.GetString("valorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor total a pagar SIN IVA es:.
        /// </summary>
        internal static string valorTotalAPagarSinIva {
            get {
                return ResourceManager.GetString("valorTotalAPagarSinIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor unitario.
        /// </summary>
        internal static string valorUnitario {
            get {
                return ResourceManager.GetString("valorUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigencia.
        /// </summary>
        internal static string vigencia {
            get {
                return ResourceManager.GetString("vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string VMaceptar {
            get {
                return ResourceManager.GetString("VMaceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cámara.
        /// </summary>
        internal static string VMCamara {
            get {
                return ResourceManager.GetString("VMCamara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres cambiar la clave de tu cuenta?.
        /// </summary>
        internal static string VMCambiarLaClaveDeCuenta {
            get {
                return ResourceManager.GetString("VMCambiarLaClaveDeCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string VMCancelar {
            get {
                return ResourceManager.GetString("VMCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Como quieres actualizar tu foto de perfil.
        /// </summary>
        internal static string VMComoQuieresCambiarTuFoto {
            get {
                return ResourceManager.GetString("VMComoQuieresCambiarTuFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        internal static string VMCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("VMCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de desvincular Apple?.
        /// </summary>
        internal static string VMDesvincularApple {
            get {
                return ResourceManager.GetString("VMDesvincularApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de desvincular Facebook?.
        /// </summary>
        internal static string VMDesvincularFacebook {
            get {
                return ResourceManager.GetString("VMDesvincularFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de desvincular Google?.
        /// </summary>
        internal static string VMDesvincularGoogle {
            get {
                return ResourceManager.GetString("VMDesvincularGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo términos y condiciones es obligatorio.
        /// </summary>
        internal static string VMElCampoTerminosEsObligatorio {
            get {
                return ResourceManager.GetString("VMElCampoTerminosEsObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico debe tener un arroba y .com, ejemplo: tucorreo@ejemplo.com.
        /// </summary>
        internal static string VMElCorreoElectronicoDebeMas {
            get {
                return ResourceManager.GetString("VMElCorreoElectronicoDebeMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener mínimo 3 caracteres.
        /// </summary>
        internal static string VMElNombreDebeTenerMinimo3Caracteres {
            get {
                return ResourceManager.GetString("VMElNombreDebeTenerMinimo3Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no se encontró.
        /// </summary>
        internal static string VMElUsuarioNoSeEncontro {
            get {
                return ResourceManager.GetString("VMElUsuarioNoSeEncontro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya esta registrado.
        /// </summary>
        internal static string VMElUsuarioYaEstaRegistrado {
            get {
                return ResourceManager.GetString("VMElUsuarioYaEstaRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estamos cargando información, revisa muy pronto.
        /// </summary>
        internal static string VMEstamosCargandoInfo {
            get {
                return ResourceManager.GetString("VMEstamosCargandoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de cerrar sesión?.
        /// </summary>
        internal static string VMEstasSegurpDeCerrarSesion {
            get {
                return ResourceManager.GetString("VMEstasSegurpDeCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario no existe en el sistema.
        /// </summary>
        internal static string VMEsteUsuaraioNoExisteMas {
            get {
                return ResourceManager.GetString("VMEsteUsuaraioNoExisteMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galería.
        /// </summary>
        internal static string VMGaleria {
            get {
                return ResourceManager.GetString("VMGaleria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres, máximo 16 caracteres, una mayúscula, una minúscula y un número.
        /// </summary>
        internal static string VMLaContrasenaDebeTenerMinimoMas {
            get {
                return ResourceManager.GetString("VMLaContrasenaDebeTenerMinimoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ha sido actualizada.
        /// </summary>
        internal static string VMLaContrasenaHaSidoActualizada {
            get {
                return ResourceManager.GetString("VMLaContrasenaHaSidoActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no se ha podido actualizar.
        /// </summary>
        internal static string VMLaContrasenaNoSeHaSidoActualizada {
            get {
                return ResourceManager.GetString("VMLaContrasenaNoSeHaSidoActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string VMLasContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("VMLasContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las correos electrónicos no coinciden.
        /// </summary>
        internal static string VMLosCorreosNoCoinciden {
            get {
                return ResourceManager.GetString("VMLosCorreosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos!! debes ser mayor de edad para poderte registrar.
        /// </summary>
        internal static string VMMayorDeEdad {
            get {
                return ResourceManager.GetString("VMMayorDeEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos tenido problemas inciando la vista del registro, intenta nuevamente o comunicate con el administrador.
        /// </summary>
        internal static string VMNoCargaVistaRegistro {
            get {
                return ResourceManager.GetString("VMNoCargaVistaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dejes campos vacíos.
        /// </summary>
        internal static string VMNoDejesCamposVacios {
            get {
                return ResourceManager.GetString("VMNoDejesCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de búsqueda no debe estar vacio.
        /// </summary>
        internal static string VMNoDejesCamposVaciosConferencista {
            get {
                return ResourceManager.GetString("VMNoDejesCamposVaciosConferencista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dejes campos obligatorios vacíos en el formulario de la empresa.
        /// </summary>
        internal static string VMNoDejesCamposVaciosEmpresa {
            get {
                return ResourceManager.GetString("VMNoDejesCamposVaciosEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dejes el campo vacío.
        /// </summary>
        internal static string VMNoDejesElCampoVacio {
            get {
                return ResourceManager.GetString("VMNoDejesElCampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han podido actualizar los datos.
        /// </summary>
        internal static string VMNoSeHanPodidoActualizarLosDatos {
            get {
                return ResourceManager.GetString("VMNoSeHanPodidoActualizarLosDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene formato el nombre del usuario.
        /// </summary>
        internal static string VMNoTieneFormaroElNombreDelUsuario {
            get {
                return ResourceManager.GetString("VMNoTieneFormaroElNombreDelUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene formato el correo electrónico.
        /// </summary>
        internal static string VMNoTieneFormatoCorreo {
            get {
                return ResourceManager.GetString("VMNoTieneFormatoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder realizar el pre-registro, debes contar con los datos completos en el perfil; por favor actualiza tu información.
        /// </summary>
        internal static string VMParaPoderRealizarElPreRegistroDatosCompletos {
            get {
                return ResourceManager.GetString("VMParaPoderRealizarElPreRegistroDatosCompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder registrarte en C-Fiel, debes contar con los datos completos en el perfil; por favor actualiza tu información.
        /// </summary>
        internal static string VMParaPoderRegistrarCfielDatosCompletos {
            get {
                return ResourceManager.GetString("VMParaPoderRegistrarCfielDatosCompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisa tu conexión a internet.
        /// </summary>
        internal static string VMRevisaTuConexion {
            get {
                return ResourceManager.GetString("VMRevisaTuConexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado la red social con éxito.
        /// </summary>
        internal static string VMSehaEliminadoLaRedSocialConExito {
            get {
                return ResourceManager.GetString("VMSehaEliminadoLaRedSocialConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio en mantenimiento, intenta de nuevo más tarde.
        /// </summary>
        internal static string VMServicioEnMantenimiento {
            get {
                return ResourceManager.GetString("VMServicioEnMantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *Zona horaria de Colombia.
        /// </summary>
        internal static string zonaHorariaColombia {
            get {
                return ResourceManager.GetString("zonaHorariaColombia", resourceCulture);
            }
        }
    }
}
